[package]
name = "movement_dex"
version = "1.0.0"
license = "MIT"

[addresses]
MovementDex = "0x42"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
